import Config

# Configure your database (SQLite for development)
config :zentinel_cp, ZentinelCp.Repo,
  database: Path.expand("../zentinel_cp_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :zentinel_cp, ZentinelCpWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "62cER6SLSxFRVRZIw30hJM/P8U7mKivZQ1/cRB+00NdHpoiowdunHjnq7Tqd2Czg",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:zentinel_cp, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:zentinel_cp, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :zentinel_cp, ZentinelCpWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/zentinel_cp_web/router\.ex$"E,
      ~r"lib/zentinel_cp_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :zentinel_cp, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Bundle storage (local filesystem in development, MinIO/S3 in production)
config :zentinel_cp, ZentinelCp.Bundles.Storage,
  backend: :local,
  local_dir: Path.expand("../priv/bundles", __DIR__)

# Bundle compiler (skip validation in dev — zentinel binary not required)
config :zentinel_cp, ZentinelCp.Bundles.Compiler,
  zentinel_binary: System.get_env("ZENTINEL_BINARY", "zentinel"),
  skip_validation: !System.get_env("ZENTINEL_BINARY")

# Use Let's Encrypt staging in development
config :zentinel_cp, :acme,
  directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"
