defmodule SentinelCp.Services.KdlGenerator do
  @moduledoc """
  Generates KDL configuration from structured service definitions.

  Pure function module — reads services and project config, produces KDL text.
  """

  alias SentinelCp.Services
  alias SentinelCp.Services.{Service, ProjectConfig, UpstreamGroup, Certificate, AuthPolicy}

  @doc """
  Generates KDL configuration for a project from its services and config.

  Returns `{:ok, kdl_string}` or `{:error, :no_services}`.
  """
  def generate(project_id) do
    services = Services.list_services(project_id, enabled: true)

    if services == [] do
      {:error, :no_services}
    else
      {:ok, config} = Services.get_or_create_project_config(project_id)
      upstream_groups = Services.list_upstream_groups(project_id)
      certificates = Services.list_certificates(project_id)
      auth_policies = Services.list_auth_policies(project_id)
      kdl = build_kdl(services, config, upstream_groups, certificates, auth_policies)
      {:ok, kdl}
    end
  end

  @doc """
  Generates KDL from provided services, config, and upstream groups (no DB access).
  Useful for testing.
  """
  def build_kdl(services, %ProjectConfig{} = config, upstream_groups \\ [], certificates \\ [], auth_policies \\ []) do
    # Build lookup maps
    group_map =
      upstream_groups
      |> Enum.into(%{}, fn g -> {g.id, g} end)

    cert_map =
      certificates
      |> Enum.into(%{}, fn c -> {c.id, c} end)

    auth_policy_map =
      auth_policies
      |> Enum.into(%{}, fn a -> {a.id, a} end)

    # Determine which certificates are used by services
    used_cert_ids =
      services
      |> Enum.map(& &1.certificate_id)
      |> Enum.reject(&is_nil/1)
      |> MapSet.new()

    used_certs = Enum.filter(certificates, fn c -> MapSet.member?(used_cert_ids, c.id) end)

    parts = [
      "// Generated by Sentinel Control Plane",
      "// Do not edit manually — managed via Services UI",
      "",
      build_settings(config),
      "",
      build_tls_certificates(used_certs),
      build_upstream_groups(upstream_groups),
      build_routes(services, group_map, cert_map, auth_policy_map),
      build_rate_limits(services)
    ]

    parts
    |> List.flatten()
    |> Enum.join("\n")
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp build_settings(%ProjectConfig{} = config) do
    lines = [
      "settings {",
      "    log_level #{inspect(config.log_level)}",
      "    metrics_port #{config.metrics_port}"
    ]

    custom_lines =
      (config.custom_settings || %{})
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "    #{key} #{format_value(value)}" end)

    lines = lines ++ custom_lines

    lines = lines ++ build_global_compression(config)
    lines = lines ++ build_global_access_control(config)
    lines = lines ++ build_global_security(config)

    lines ++ ["}"]
  end

  defp build_global_compression(%ProjectConfig{} = config) do
    build_nested_map_block(config.default_compression, "compression", "    ")
  end

  defp build_global_access_control(%ProjectConfig{} = config) do
    build_nested_map_block(config.global_access_control, "access_control", "    ")
  end

  defp build_global_security(%ProjectConfig{} = config) do
    build_nested_map_block(config.default_security, "security", "    ")
  end

  defp build_upstream_groups([]), do: []

  defp build_upstream_groups(groups) do
    blocks =
      groups
      |> Enum.map(&build_upstream_group_block/1)
      |> Enum.intersperse([""])

    ["upstream_groups {"] ++ List.flatten(blocks) ++ ["}", ""]
  end

  defp build_upstream_group_block(%UpstreamGroup{} = group) do
    lines = ["    group #{inspect(group.slug)} {"]
    lines = lines ++ ["        algorithm #{inspect(group.algorithm)}"]

    # Add targets
    targets = group.targets || []

    target_lines =
      Enum.map(targets, fn t ->
        base = "        target #{inspect(t.host)} #{t.port}"
        base = if t.weight != 100, do: "#{base} weight=#{t.weight}", else: base
        base
      end)

    lines = lines ++ target_lines

    # Add health check
    lines = lines ++ build_nested_map_block(group.health_check, "health_check", "        ")

    # Add circuit breaker
    lines = lines ++ build_nested_map_block(group.circuit_breaker, "circuit_breaker", "        ")

    # Add sticky sessions
    lines = lines ++ build_nested_map_block(group.sticky_sessions, "sticky_sessions", "        ")

    lines ++ ["    }"]
  end

  defp build_routes(services, group_map, cert_map, auth_policy_map) do
    route_blocks =
      services
      |> Enum.map(&build_route(&1, group_map, cert_map, auth_policy_map))
      |> Enum.intersperse([""])

    ["routes {"] ++ List.flatten(route_blocks) ++ ["}"]
  end

  defp build_route(%Service{} = service, group_map, cert_map, auth_policy_map) do
    lines = ["    route #{inspect(service.route_path)} {"]

    lines =
      cond do
        service.upstream_url ->
          lines ++ ["        upstream #{inspect(service.upstream_url)}"]

        service.upstream_group_id && Map.has_key?(group_map, service.upstream_group_id) ->
          group = Map.get(group_map, service.upstream_group_id)
          lines ++ ["        upstream_group #{inspect(group.slug)}"]

        service.redirect_url ->
          status = service.respond_status || 301
          lines ++ ["        redirect #{status} #{inspect(service.redirect_url)}"]

        true ->
          lines ++
            ["        respond #{service.respond_status} #{inspect(service.respond_body || "")}"]
      end

    lines =
      if service.timeout_seconds do
        lines ++ ["        timeout #{service.timeout_seconds}s"]
      else
        lines
      end

    lines = lines ++ build_retry_block(service.retry)
    lines = lines ++ build_cache_block(service.cache)
    lines = lines ++ build_health_check_block(service.health_check)
    lines = lines ++ build_headers_block(service.headers)
    lines = lines ++ build_cors_block(service.cors)
    lines = lines ++ build_access_control_block(service.access_control)
    lines = lines ++ build_compression_block(service.compression)
    lines = lines ++ build_path_rewrite_block(service.path_rewrite)
    lines = lines ++ build_tls_ref(service.certificate_id, cert_map)
    lines = lines ++ build_auth_block(service.auth_policy_id, auth_policy_map)
    lines = lines ++ build_security_block(service.security)
    lines = lines ++ build_request_transform_block(service.request_transform)
    lines = lines ++ build_response_transform_block(service.response_transform)

    lines ++ ["    }"]
  end

  defp build_retry_block(retry) when retry == %{} or retry == nil, do: []

  defp build_retry_block(retry) do
    build_nested_map_block(retry, "retry", "        ")
  end

  defp build_cache_block(cache) when cache == %{} or cache == nil, do: []

  defp build_cache_block(cache) do
    build_nested_map_block(cache, "cache", "        ")
  end

  defp build_health_check_block(hc) when hc == %{} or hc == nil, do: []

  defp build_health_check_block(hc) do
    build_nested_map_block(hc, "health_check", "        ")
  end

  defp build_headers_block(headers) when headers == %{} or headers == nil, do: []

  defp build_headers_block(headers) do
    build_nested_map_block(headers, "headers", "        ")
  end

  defp build_cors_block(cors) when cors == %{} or cors == nil, do: []

  defp build_cors_block(cors) do
    build_nested_map_block(cors, "cors", "        ")
  end

  defp build_access_control_block(ac) when ac == %{} or ac == nil, do: []

  defp build_access_control_block(ac) do
    build_nested_map_block(ac, "access_control", "        ")
  end

  defp build_compression_block(comp) when comp == %{} or comp == nil, do: []

  defp build_compression_block(comp) do
    build_nested_map_block(comp, "compression", "        ")
  end

  defp build_path_rewrite_block(pr) when pr == %{} or pr == nil, do: []

  defp build_path_rewrite_block(pr) do
    build_nested_map_block(pr, "path_rewrite", "        ")
  end

  defp build_nested_map_block(map, _name, _indent) when map == %{} or map == nil, do: []

  defp build_nested_map_block(map, name, indent) do
    inner =
      map
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "#{indent}    #{key} #{format_value(value)}" end)

    if inner == [] do
      []
    else
      ["#{indent}#{name} {"] ++ inner ++ ["#{indent}}"]
    end
  end

  defp build_tls_certificates([]), do: []

  defp build_tls_certificates(certs) do
    blocks =
      certs
      |> Enum.map(&build_tls_certificate_block/1)
      |> Enum.intersperse([""])

    ["tls {"] ++ List.flatten(blocks) ++ ["}", ""]
  end

  defp build_tls_certificate_block(%Certificate{} = cert) do
    lines = ["    certificate #{inspect(cert.slug)} {"]
    lines = lines ++ ["        domain #{inspect(cert.domain)}"]
    lines = lines ++ ["        cert_file \"/etc/sentinel/certs/#{cert.slug}.pem\""]
    lines = lines ++ ["        key_file \"/etc/sentinel/certs/#{cert.slug}.key\""]

    lines =
      if cert.san_domains && cert.san_domains != [] do
        sans = Enum.map_join(cert.san_domains, " ", &inspect/1)
        lines ++ ["        san_domains #{sans}"]
      else
        lines
      end

    lines ++ ["    }"]
  end

  defp build_tls_ref(nil, _cert_map), do: []

  defp build_tls_ref(cert_id, cert_map) do
    case Map.get(cert_map, cert_id) do
      nil ->
        []

      cert ->
        [
          "        tls {",
          "            certificate #{inspect(cert.slug)}",
          "        }"
        ]
    end
  end

  defp build_security_block(sec) when sec == %{} or sec == nil, do: []

  defp build_security_block(sec) do
    build_nested_map_block(sec, "security", "        ")
  end

  defp build_request_transform_block(rt) when rt == %{} or rt == nil, do: []

  defp build_request_transform_block(rt) do
    build_nested_map_block(rt, "request_transform", "        ")
  end

  defp build_response_transform_block(rt) when rt == %{} or rt == nil, do: []

  defp build_response_transform_block(rt) do
    build_nested_map_block(rt, "response_transform", "        ")
  end

  defp build_auth_block(nil, _auth_policy_map), do: []

  defp build_auth_block(auth_policy_id, auth_policy_map) do
    case Map.get(auth_policy_map, auth_policy_id) do
      nil ->
        []

      %AuthPolicy{} = policy ->
        lines = ["        auth {"]
        lines = lines ++ ["            type #{inspect(policy.auth_type)}"]

        config_lines =
          (policy.config || %{})
          |> Enum.sort_by(fn {k, _} -> k end)
          |> Enum.map(fn {key, value} -> "            #{key} #{format_value(value)}" end)

        lines = lines ++ config_lines
        lines ++ ["        }"]
    end
  end

  defp build_rate_limits(services) do
    rate_limited =
      services
      |> Enum.filter(fn s -> s.rate_limit && s.rate_limit != %{} end)

    if rate_limited == [] do
      []
    else
      blocks =
        rate_limited
        |> Enum.map(&build_rate_limit_entry/1)
        |> Enum.intersperse([""])

      ["", "rate_limits {"] ++ List.flatten(blocks) ++ ["}"]
    end
  end

  defp build_rate_limit_entry(%Service{} = service) do
    inner =
      service.rate_limit
      |> Enum.sort_by(fn {k, _} -> k end)
      |> Enum.map(fn {key, value} -> "        #{key} #{format_value(value)}" end)

    ["    limit #{inspect(service.slug)} {"] ++ inner ++ ["    }"]
  end

  defp format_value(value) when is_binary(value), do: inspect(value)
  defp format_value(value) when is_integer(value), do: Integer.to_string(value)
  defp format_value(value) when is_float(value), do: Float.to_string(value)
  defp format_value(true), do: "true"
  defp format_value(false), do: "false"
  defp format_value(value) when is_list(value), do: inspect(value)
  defp format_value(value), do: inspect(value)
end
